// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAkgUvuyGY-oInZJBK4bMdgZ-_NkeUkAA',
    appId: '1:968408128089:web:9a20da9c4b241cdeddef48',
    messagingSenderId: '968408128089',
    projectId: 'cosmoquest-c6268',
    authDomain: 'cosmoquest-c6268.firebaseapp.com',
    storageBucket: 'cosmoquest-c6268.appspot.com',
    measurementId: 'G-FE2VSH1YF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxojpjFMRuSKG_mRIl5Wzl7wWA8l_FgI',
    appId: '1:968408128089:android:f22b142c35cfe09bddef48',
    messagingSenderId: '968408128089',
    projectId: 'cosmoquest-c6268',
    storageBucket: 'cosmoquest-c6268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHQmDUxrFYsLeiurPL38jR84OuP8rvtHM',
    appId: '1:968408128089:ios:2c3369dd449029cbddef48',
    messagingSenderId: '968408128089',
    projectId: 'cosmoquest-c6268',
    storageBucket: 'cosmoquest-c6268.appspot.com',
    iosBundleId: 'com.example.cosmoquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHQmDUxrFYsLeiurPL38jR84OuP8rvtHM',
    appId: '1:968408128089:ios:2c3369dd449029cbddef48',
    messagingSenderId: '968408128089',
    projectId: 'cosmoquest-c6268',
    storageBucket: 'cosmoquest-c6268.appspot.com',
    iosBundleId: 'com.example.cosmoquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAkgUvuyGY-oInZJBK4bMdgZ-_NkeUkAA',
    appId: '1:968408128089:web:d3c91c264302e86cddef48',
    messagingSenderId: '968408128089',
    projectId: 'cosmoquest-c6268',
    authDomain: 'cosmoquest-c6268.firebaseapp.com',
    storageBucket: 'cosmoquest-c6268.appspot.com',
    measurementId: 'G-BLBJFEDGHM',
  );
}
